# Generated by Django 5.2.4 on 2025-07-20 08:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_team_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('usernum', models.AutoField(db_column='userNum', primary_key=True, serialize=False)),
                ('id', models.CharField(db_column='id', max_length=12)),
                ('teamnum', models.ForeignKey(db_column='teamNum', on_delete=django.db.models.deletion.CASCADE, related_name='Team', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='task',
            fields=[
                ('tasknum', models.AutoField(db_column='taskNum', primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('do', models.BooleanField(default=False)),
                ('import_field', models.IntegerField(db_column='import', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('usernum', models.ForeignKey(db_column='userNum', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Member', to='users.member')),
            ],
            options={
                'ordering': ['-import_field'],
            },
        ),
    ]
