# Generated by Django 5.2.4 on 2025-07-27 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_member_id_member_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='userId',
        ),
        migrations.AlterField(
            model_name='member',
            name='teamnum',
            field=models.ForeignKey(db_column='teamNum', on_delete=django.db.models.deletion.CASCADE, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='usernum',
            field=models.ForeignKey(db_column='userNum', on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks', to='users.member'),
        ),
        migrations.AddField(
            model_name='member',
            name='userID',
            field=models.CharField(db_column='userID', default=1, max_length=12),
            preserve_default=False,
        ),
    ]
