# Generated by Django 5.2.4 on 2025-07-30 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_member_userid_alter_member_teamnum_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('teamnum', 'userID')},
        ),
    ]
