# Generated by Django 5.2.4 on 2025-07-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_member_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='id',
        ),
        migrations.AddField(
            model_name='member',
            name='userId',
            field=models.CharField(db_column='userId', default=1, max_length=12),
            preserve_default=False,
        ),
    ]
