# Generated by Django 5.2.4 on 2025-08-06 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_member_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-priority']},
        ),
        migrations.RenameField(
            model_name='member',
            old_name='teamnum',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='usernum',
            new_name='userNum',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='do',
            new_name='done',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='import_field',
            new_name='priority',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='tasknum',
            new_name='taskNum',
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('team', 'userID')},
        ),
        migrations.AlterField(
            model_name='task',
            name='usernum',
            field=models.ForeignKey(db_column='userNum', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='users.member'),
        ),
    ]
